release fetcher in nonCancellable scope
dropbox/Store pull request #432
Opened 2022-04-16 21:25 UTC by lukisk

Fixes issue: #429

2022-04-16 21:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dropbox/Store?pullRequest=432) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dropbox/Store?pullRequest=432) before we can accept your contribution.<br/><hr/>**luki** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dropbox/Store?pullRequest=432) it.</sub>

2022-04-20 17:21 UTC, digitalbuddha commented
lgtm, I can't approve as not at dropbox anymore :-) maybe @rharter can take care of merging?

2022-04-21 10:59 UTC, rharter approved these changes

2022-04-21 11:39 UTC, rharter requested changes
Looks like you'll just have to fix that wildcard import so code style checks pass.

2022-04-23 00:20 UTC, rharter approved these changes

2022-04-23 00:20 UTC, merged